name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - run: |
        pip install sphinx
        make doc

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    # - name: Lint with isort
    #   run: |
    #     # For isort, must install all "system" dependencies
    #     pip install .[all]
    #     pip install pytest
    #     pip install isort
    #     isort -rc --check .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # VTK is missing for Python 3.9
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Test with tox
      run: |
        pip install tox
        tox
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.8' }}
